apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-prj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-prj
  template:
    metadata:
      labels:
        app: cloud-prj
    spec:
      containers:
        - name: cloud-prj
          image: syedasumiyabukhari/cloud-prj:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
